/**
 * Cavalry Generator — CompiledPlan → Cavalry JS string.
 *
 * THIS IS THE ONLY LAYER THAT REFERENCES THE CAVALRY `api.*` NAMESPACE.
 * Adding `api.*` references anywhere else in the compiler is a contract
 * violation (see CLAUDE.md "API Grounding Layer Rule").
 *
 * v1 emits only the API surface verified in CLAUDE.md / ACTIVE_CONTEXT.md:
 *   - api.set
 *   - api.keyframe
 *   - api.magicEasing
 *
 * Layer creation, scene queries, and `api.log()`-dependent flows are NOT
 * emitted — those depend on behaviors not yet verified for Stallion v0.7.
 */

import type {
  CompiledPlan,
  ControlledAttr,
  EasingType,
  MotionOp,
  ResolvedTarget,
} from "./motionDSL.js";

export class GeneratorError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "GeneratorError";
  }
}

// ---------------------------------------------------------------------------
// Target ref → Cavalry layer-id resolution
// ---------------------------------------------------------------------------

function resolveTargetIdLiteral(target: ResolvedTarget["target"]): string {
  if (target.kind === "existingLayerById") {
    return JSON.stringify(target.id);
  }
  // existingLayerByName is intentionally unsupported in v1: there is no
  // verified scene-query API path that we can emit without speculation.
  throw new GeneratorError(
    `Target kind "${target.kind}" not supported by v1 generator. ` +
      `Use { kind: "existingLayerById", id } instead.`,
  );
}

// ---------------------------------------------------------------------------
// Op grouping — combine keyframes with the same (targetRef, frame) into a
// single `api.keyframe(id, frame, { ... })` call. Matches the documented
// Cavalry signature and keeps the emitted code compact.
// ---------------------------------------------------------------------------

interface KeyframeBucket {
  targetRef: string;
  frame: number;
  attrs: Record<ControlledAttr, number>;
}

function bucketKey(targetRef: string, frame: number): string {
  return `${targetRef}@${frame}`;
}

function groupOps(ops: MotionOp[]): {
  setOps: Extract<MotionOp, { kind: "setAttr" }>[];
  keyframeBuckets: KeyframeBucket[];
  easingOps: Extract<MotionOp, { kind: "easing" }>[];
} {
  const setOps: Extract<MotionOp, { kind: "setAttr" }>[] = [];
  const easingOps: Extract<MotionOp, { kind: "easing" }>[] = [];
  const buckets = new Map<string, KeyframeBucket>();

  for (const op of ops) {
    switch (op.kind) {
      case "setAttr":
        setOps.push(op);
        break;
      case "keyframe": {
        const key = bucketKey(op.targetRef, op.frame);
        const existing = buckets.get(key);
        if (existing) {
          existing.attrs[op.attr] = op.value;
        } else {
          buckets.set(key, {
            targetRef: op.targetRef,
            frame: op.frame,
            attrs: { [op.attr]: op.value } as Record<ControlledAttr, number>,
          });
        }
        break;
      }
      case "easing":
        easingOps.push(op);
        break;
    }
  }

  return {
    setOps,
    keyframeBuckets: Array.from(buckets.values()),
    easingOps,
  };
}

// ---------------------------------------------------------------------------
// Code emission
// ---------------------------------------------------------------------------

function emitJsLiteral(value: number | string | EasingType): string {
  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new GeneratorError(`refusing to emit non-finite number ${value}`);
    }
    return String(value);
  }
  return JSON.stringify(value);
}

function emitAttrMap(attrs: Record<string, number>): string {
  const parts = Object.entries(attrs).map(
    ([k, v]) => `${JSON.stringify(k)}: ${emitJsLiteral(v)}`,
  );
  return `{ ${parts.join(", ")} }`;
}

/**
 * Generate Cavalry-ready JavaScript for a compiled plan.
 *
 * Output shape:
 *   const __t0 = "<layerId>";
 *   api.set(__t0, { ... });          // when there are setAttr ops
 *   api.keyframe(__t0, <frame>, { ... });
 *   api.magicEasing(__t0, "<attr>", <frame>, "<easing>");
 */
export function generate(plan: CompiledPlan): string {
  const lines: string[] = [];

  // Header — purely informational; Cavalry ignores comments at runtime.
  lines.push("// generated by motion-compiler v1");
  lines.push("// do not hand-edit; regenerate from the MotionProgram source");
  lines.push("");

  // Target id resolution preamble
  const refToVar = new Map<string, string>();
  for (const t of plan.targets) {
    const varName = `__${t.ref}`;
    refToVar.set(t.ref, varName);
    const idLiteral = resolveTargetIdLiteral(t.target);
    lines.push(`const ${varName} = ${idLiteral};`);
  }
  if (plan.targets.length > 0) lines.push("");

  const refVar = (ref: string): string => {
    const v = refToVar.get(ref);
    if (!v) {
      throw new GeneratorError(`unresolved target ref: ${ref}`);
    }
    return v;
  };

  const { setOps, keyframeBuckets, easingOps } = groupOps(plan.ops);

  // setAttr — group by targetRef into a single api.set call per target
  if (setOps.length > 0) {
    const setByTarget = new Map<string, Record<string, number>>();
    for (const op of setOps) {
      const map = setByTarget.get(op.targetRef) ?? {};
      map[op.attr] = op.value;
      setByTarget.set(op.targetRef, map);
    }
    for (const [ref, attrs] of setByTarget) {
      lines.push(`api.set(${refVar(ref)}, ${emitAttrMap(attrs)});`);
    }
    lines.push("");
  }

  // keyframes — sorted by (ref, frame) for deterministic output
  const sortedBuckets = [...keyframeBuckets].sort((a, b) => {
    if (a.targetRef !== b.targetRef)
      return a.targetRef < b.targetRef ? -1 : 1;
    return a.frame - b.frame;
  });
  for (const bucket of sortedBuckets) {
    lines.push(
      `api.keyframe(${refVar(bucket.targetRef)}, ${bucket.frame}, ${emitAttrMap(bucket.attrs)});`,
    );
  }
  if (sortedBuckets.length > 0) lines.push("");

  // easing — sorted for determinism
  const sortedEasing = [...easingOps].sort((a, b) => {
    if (a.targetRef !== b.targetRef)
      return a.targetRef < b.targetRef ? -1 : 1;
    if (a.attr !== b.attr) return a.attr < b.attr ? -1 : 1;
    return a.frame - b.frame;
  });
  for (const op of sortedEasing) {
    lines.push(
      `api.magicEasing(${refVar(op.targetRef)}, ${JSON.stringify(op.attr)}, ${op.frame}, ${JSON.stringify(op.type)});`,
    );
  }

  return lines.join("\n").trimEnd() + "\n";
}
